blog/urls.py
from django.urls import path
from . import views

app_name="blog"
urlpatterns = [
    path('',views.article_view, name="article"),
    path('<int:pk>',views.detail, name="detail"),
    path('create/',views.create, name="create"),
    path('admin/',views.admin, name="admin"),
    path('admin/<int:pk>/',views.edit, name="edit"),
    path('admin/update_or_delete/<int:pk>',views.update_or_delete, name="update_or_delete"),
]

dj_GCE/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("signup.urls")),
    path('blog/', include("blog.urls")),
]

signup/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "signup"
urlpatterns = [
    path('', views.index, name="index"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
]

blog/models.py
from time import timezone
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone
User = get_user_model()

class Article(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=30)
    body = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(default=timezone.now)

    def __str__(self) -> str:
        return self.title
# Create your models here.

signup/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser, PermissionsMixin
)
from django.utils import timezone

class UserManager(BaseUserManager):
    use_in_migrations=True

    def _create_user(self, email, password, **kwargs):
        if not email:
            raise ValueError("Email error")
        email = self.normalize_email(email)

        user = self.model(email=email, **kwargs)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_uesr(self, email, password, **kwargs):
        kwargs.setdefault("is_staff", False)
        kwargs.setdefault("is_superuser", False)
        return self._create_user(email, password, **kwargs)

    def create_superuser(self, email, password, **kwargs):#管理者アカウント作成
        kwargs.setdefault("is_staff", True)
        kwargs.setdefault("is_superuser", True)
        if kwargs.get("is_staff") is not True:
            raise ValueError("superuser must be is_staff=True")
        
        if kwargs.get("is_superuser") is not True:
            raise ValueError("superuser must be is_superuser=True")
        return self._create_user(email, password, **kwargs)


class User(AbstractBaseUser, PermissionsMixin):
    #データベースのテーブルの列名
    email = models.EmailField(max_length=255, unique=True)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(default=timezone.now)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    objects = UserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email


# Create your models here.

blog/forms.py
from django import forms
from .models import Article


class ArticleCreateForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ("title", "body")

signup/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
User = get_user_model()


class UserCreateForm(UserCreationForm):

    class Meta:
        model = User
        fields = ("email", )

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        

blog/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .models import Article
from .forms import ArticleCreateForm

def article_view(request):
    articles = Article.objects.all().order_by("-created_at")
    context = {"articles": articles}
    return render(request, "blog/article.html", context)


def detail(request, pk: int):
    article = Article.objects.get(pk=pk)
    context = {"article": article}
    return render(request, "blog/detail.html", context)

@login_required
def create(request):
    if request.method == "GET":
        context = {"form": ArticleCreateForm}
        return render(request, "blog/create.html", context)
    else:
        form = ArticleCreateForm(request.POST)
        if form.is_valid:
            article = form.save(commit=False)
            article.author = request.user
            article.save()
            articles = Article.objects.all().order_by("-created_at")
            context = {"articles": articles}
            return render(request, "blog/article.html",context)
        else:
            return render(request, "blog/create.html")

@login_required
def admin(request):
    if request.method == "GET":
        articles = Article.objects.filter(author=request.user).order_by("-created_at")
        context = {"articles": articles, "admin":True}
        return render(request, "blog/article.html", context)


@login_required
def edit(request, pk: int):
    if request.method == "GET":
       article = Article.objects.get(author=request.user, pk=pk)
       context = {"article": article}
       return render(request, "blog/edit.html", context) 

@login_required
def update_or_delete(request, pk: int):
    if request.method == "POST":
        article = Article.objects.get(author=request.user,pk=pk)
        if "update" in request.POST:
            article.title = request.POST["title"]
            article.title = request.POST["body"]
            article.save()
        elif "delete" in request.POST:
            article.delete()
        articles = Article.objects.filter(author=request.user).order_by("-created_at")
        context = {"articles": articles, "admin":True}
    return render(request, "blog/article.html", context)
# Create your views here.

signup/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth import login, logout, authenticate
from .forms import UserCreateForm

def index(request):
    if request.method == "GET":
        context = {"form": UserCreateForm}
        return render(request, "signup/home.html", context)
    form = UserCreateForm(request.POST)
    if form.is_valid():
        form.save()
        return render(request, "signup/home.html")
    else:
        return render(request, "signup/home.html", {"form": form})

def login_view(request):
    if request.method == "GET":
        return render(request,"signup/login.html")
    
    email=request.POST["email"]
    password=request.POST["password"]
    user = authenticate(request, email=email, password=password)
    #login(request, user)
    return render(request,"signup/login.html")

def logout_view(request):
    logout(request)
    return render(request, "signup/login.html")
# Create your views here.

blog/templates/blog/article.html
{% extends "base.html" %}
{% block content %}
<h1>Blog Page</h1>
{% for article in articles%}
    {% if admin %}
        pk: <a href="{% url 'blog:edit' article.pk%}">{{ article.pk}}</a><br>
    {% else %}
        pk: <a href="{% url 'blog:detail' article.pk%}">{{ article.pk}}</a><br>
    {% endif %}
    title: {{ article.title}}<br>
{% endfor %}
{% endblock %}

blog/templates/blog/create.html
{% extends "base.html" %}
{% block content %}
<h1>Post</h1>
<form action="{% url 'blog:create' %}" method="POST">
    {% for field in form %}
        <label>{{ field.label_tag }}</label>
        {{ field }}
        <br><br>
        {% endfor %}
    <button type="submit">Post</button>
    {% csrf_token %}
</form>
{% endblock %}

blog/templates/blog/detail.html
{% extends "base.html" %}
{% block content %}
<h1>Detail Page</h1>
<table>
    <tr>
        <th>Title</th>
        <td>{{ article.title }}</td>
    </tr>
    <tr>
        <th>Body</th>
        <td>{{ article.body }}</td>
    </tr>
    <tr>
        <th>Created_at</th>
        <td>{{ article.created_at }}</td>
    </tr>
</table>

{% endblock %}

blog/templates/blog/edit.html
{% extends "base.html" %}
{% block content %}
<h1>Edit Page</h1>
<form action="{% url 'blog:update_or_delete' article.pk %}" method="POST">
    <table>
        <tr>
            <th>Title</th>
            <td><input name="title" value="{{ article.title }}"></td>
        </tr>
        <tr>
            <th>Body</th>
            <td><td><input name="body" value="{{ article.body }}"></td></td>
        </tr>
        <tr>
            <th>Created_at</th>
            <td>{{ article.created_at }}</td>
        </tr>
    </table>
    {% csrf_token %}
    <button type="submit" name="update" onclick="return confirm('Edit?')">Edit</button>
    <br><br>
    <button type="submit" name="delete" onclick="return confirm('Delete?')">Delete</button>
</form>


{% endblock %}

signup/templates/signup/home.html
{% extends "base.html" %}
{% block content %}
<h1>SignUp Page</h1>
{% if user.is_authenticated %}
    Hello {{ user.email }}
{% else %}
    <form action="{% url 'signup:index' %}" method="POST">
        {{ form }}
        <button type="submit">Sign up</button>
        {% csrf_token %}
    </form>
{% endif %}
{% endblock %}

signup/templates/signup/login.html
{% extends "base.html" %}
{% block content %}
<h1>Login Page</h1>
<form action="{% url 'signup:login'%}" method="POST">
    Email: <input type="text" name="email">
    <br>
    Passoword: <input type="text" name="password">
    <br>
    <button type="submit">Login</button>
    <br>
    {% csrf_token %}
</form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    <a href="{% url 'blog:article'%}">Blog</a>
    {% if user.is_authenticated %}
        <a href="{% url 'blog:admin'%}">Admin</a>
        <a href="{% url 'blog:create'%}">Post</a>
        <a href="{% url 'signup:logout'%}">logout</a>
    {% else %}
        <a href="{% url 'signup:index'%}">signup</a>
        <a href="{% url 'signup:login'%}">login</a>
    {% endif %}
    {% block content %}{% endblock %}
    <footer>
        <h1>Footer</h1>
    </footer>
    {% csrf_token%}
</body>
</html>